//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authored
    {
        public int AuthoredId { get; set; }
        public int WriterId { get; set; }
        public int ComicBookId { get; set; }
        public int WriterWriterId { get; set; }
        public int ComicBookComicBookId { get; set; }
    
        public virtual Writer Writer { get; set; }
        public virtual ComicBook ComicBook { get; set; }
    }
}
