//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComicBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComicBook()
        {
            this.Authoreds = new HashSet<Authored>();
        }
    
        public int ComicBookId { get; set; }
        public string Title { get; set; }
        public System.DateTime Published { get; set; }
        public int PublisherPublisherId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authored> Authoreds { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
